pcs/pcs/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^pronto/', include('pronto.urls', namespace="pronto")),
    url(r'^admin/', admin.site.urls),
]

pcs/pronto/urls.py
from django.conf.urls import url

from . import views

app_name = 'pronto'
urlpatterns = [
    url(r'^index$', views.index, name='index'),

    url(r'^update_pronto$', views.update_pronto, name='update_pronto'),
    url(r'^create_or_update_pronto$', views.create_or_update_pronto, name='create_or_update_pronto'),

    url(r"^render_pronto_statics$", views.render_pronto_statics, name="render_pronto_statics"),
    url(r"^render_pronto_charting$", views.render_pronto_charting, name="render_pronto_charting"),

    url(r"^get_pronto_woh$", views.get_pronto_woh, name="get_pronto_woh"),
    url(r'^get_pronto_all$', views.get_pronto_all, name='get_pronto_all'),
    url(r"^get_pronto_top$", views.get_pronto_top, name="get_pronto_top"),
    url(r"^get_pronto_time$", views.get_pronto_time, name="get_pronto_time"),
    url(r"^get_pronto_ratio$", views.get_pronto_ratio, name="get_pronto_ratio"),
    url(r"^get_pronto_report$", views.get_pronto_report, name="get_pronto_report"),
    url(r"^get_pronto_charting$", views.get_pronto_charting, name="get_pronto_charting"),
    url(r"^get_pronto_charting_day$", views.get_pronto_charting_day, name="get_pronto_charting_day"),
    url(r"^get_pronto_priority$", views.get_pronto_priority, name="get_pronto_priority"),
    url(r"^get_pronto_not_done$", views.get_pronto_not_done, name="get_pronto_not_done"),
    url(r"^delete_pronto$", views.delete_pronto, name="delete_pronto$"),
]

pcs/pronto/models.py
import json
import datetime

from django.db import models
from django.utils import timezone


class Pronto(models.Model):
    pronto_id = models.TextField()

    release = models.TextField(null=True, blank=True)
    feature = models.TextField(null=True, blank=True)
    title = models.TextField(null=True, blank=True)
    build = models.TextField(null=True, blank=True)
    severity = models.TextField(null=True, blank=True)
    responsible_person = models.TextField(max_length=50, null=True, blank=True)
    status = models.TextField(null=True, blank=True)

    transfer_from = models.TextField(null=True, blank=True)
    transfer_to = models.TextField(null=True, blank=True)

    rca_state = models.TextField(null=True, blank=True)

    reported_date = models.DateTimeField('Reported Date', null=True, blank=True)
    rft_date = models.DateTimeField('RFT Date', null=True, blank=True)
    in_date = models.DateTimeField('In Date', null=True, blank=True)
    out_date = models.DateTimeField('Out Date', null=True, blank=True)
    root_cause_found_date = models.DateTimeField('Root Cause Found Date', null=True, blank=True)

    is_top = models.TextField(default="false", null=True, blank=True)

    group_idx = models.TextField(null=True, blank=True)

    def was_reported_recently(self):
        now = timezone.now()
        if self.reported_date:
            return now - datetime.timedelta(days=7) < self.reported_date < now

    was_reported_recently.admin_order_field = 'pub_date'
    was_reported_recently.boolean = True
    was_reported_recently.short_description = 'Published recently?'

    def to_json(self):
        return json.dumps(dict([(attr, getattr(self, attr))
                                for attr in [f.name for f in self._meta.fields]]), cls=DateEncoder)

    def time_rft(self):
        if self.rft_date:
            return (self.rft_date - self.in_date).days
        else:
            return (self.out_date - self.in_date).days

    def time_test(self):
        if self.rft_date:
            return (self.out_date - self.rft_date).days
        else:
            return (self.out_date - self.out_date).days

    def __str__(self):
        return self.pronto_id

pcs/pronto/views.py
from django.shortcuts import render
from django.views.decorators.cache import cache_page

from .lib.http import *
from .lib.mail import *
from .lib.cache import *
from .lib.prontos import *


@cache_page(CACHE_TIME)
def index(request):
    return render(request, 'pronto/index.html', {"pronto_fields": get_pronto_fields()})

def update_pronto(request):
    idx = int(request.POST.get('content[id]'))
    pronto_instance = Pronto.objects.get(id=idx)
    for field in request.POST:
        if "content" in field:
            setattr(pronto_instance, field.split("[")[-1][:-1], request.POST.get(field))
    pronto_instance.save()
    return HttpResponse(pronto_instance.to_json(), content_type="application/json")


def create_or_update_pronto(request):
    clear_cache()
    pronto_info_dic = get_dic_from_json(request.body)
    update_prontos_fields(pronto_info_dic)
    return http_reponse()


@cache_page(CACHE_TIME)
def render_pronto_statics(request):
    return render(request, 'pronto/static.html')


@cache_page(CACHE_TIME)
def render_pronto_charting(request):
    return render(request, 'pronto/charting.html', {"pronto_fields": get_pronto_fields()})


def get_pronto_woh(request):
    return http_response_with_json(get_current_week_pronto_status())


def get_pronto_all(request):
    req_filter = request.GET
    return http_response_with_json(get_pronto_with_fitler(req_filter))


def get_pronto_top(request):
    return http_response_with_json(get_prontos_top())


def get_pronto_time(request):
    return http_response_with_json(get_prontos_time())


def get_pronto_ratio(request):
    attribute = request.GET["attribute"]
    return http_response_with_json(get_prontos_ratio(attribute))


def get_pronto_report(request):
    send_prontos_report()
    return http_reponse("<h1>Mail Sent Successfully!</h1>")


def get_pronto_charting(request):
    return http_response_with_json(get_prontos_charting())

def get_pronto_charting_day(request):
    return http_response_with_json(get_prontos_charting_day())

def get_pronto_priority(request):
    return http_response_with_json(get_prontos_priority())

def delete_pronto(request):
    pronto_id = request.GET.get("pronto_id")
    return  http_response_with_json(delete_prontos(pronto_id))


def get_pronto_not_done(request):
    group = request.GET.get("group")
    return http_response_with_json(get_prontos_not_done(group))

pcs/pronto/templates/pronto/charting.html
<!doctype html>
<html>
{% load static %}
    <head>
        <script type="text/javascript" src="{% static 'pronto/js/jquery.min.js' %}"></script>
        <script type="text/javascript" src="{% static 'pronto/js/highcharts.js' %}"></script>
        <script type="text/javascript" src="{% static 'pronto/js/exporting.js' %}"></script>
        <script type="text/javascript" src="{% static 'pronto/js/charting.js' %}"></script>
        <link type="text/css" rel="stylesheet" href="{% static 'pronto/js/jsgrid-1.5.3/jsgrid.min.css' %}" />
        <link type="text/css" rel="stylesheet" href="{% static 'pronto/js/jsgrid-1.5.3/jsgrid-theme.min.css' %}" />
        <script type="text/javascript" src="{% static 'pronto/js/jsgrid-1.5.3/jsgrid.min.js' %}"></script>
        <script type="text/javascript" src="{% static 'pronto/js/main.js' %}"></script>
        <link type="text/css" rel="stylesheet" href="{% static 'pronto/css/main.css' %}" />
        <title>Pronto Collection Statics Page</title>
    </head>
    <body>
        {% csrf_token %}
        <div class ="main">
            <div class="header_left" >
                <div class="logo">
                    <img src= "{% static 'pronto/img/Nokia_logo.png' %}" width="220px" height="50px" border="0" alt="NOKIA" title="NOKIA">
                </div>
            </div>
            <div class="head-right" >
                <div class="content-top">
                    <div class="global_links f-right topNavBg">
                        <a href="{% url 'pronto:index' %}">Main</a>
                        <a href="{% url 'pronto:render_pronto_statics' %}">Static</a>
                    </div>
                </div>
            </div>
            <div class="header_below">
                <ul>
                {% for filed_name in pronto_fields %}
                    <li><input type = "checkbox" name="{{ filed_name }}" id="{{ forloop.counter0 }}" value="{{ filed_name }}" onChange="chk({{ forloop.counter0 }},'{{ filed_name }}')" checked="checked"/> {{filed_name}}</li>
                {% endfor %}
                </ul>
            </div>
            <div id="container_line_char" class="container_line_char">
                <script type="text/javascript">pronto_chart();</script>
            </div>
            <div id="jsGrid"></div>
            <script type="text/javascript">get_pronto_with_condition('get_pronto_woh', false);</script>
        </div>
    </body>
</html>

pcs/pronto/templates/pronto/index.html
<!doctype html>
<html>
{% load static %}
    <head>
        <link type="text/css" rel="stylesheet" href="{% static 'pronto/js/jsgrid-1.5.3/jsgrid.min.css' %}" />
        <link type="text/css" rel="stylesheet" href="{% static 'pronto/js/jsgrid-1.5.3/jsgrid-theme.min.css' %}" />
        <script type="text/javascript" src="{% static 'pronto/js/jquery.min.js' %}"></script>
        <script type="text/javascript" src="{% static 'pronto/js/jsgrid-1.5.3/jsgrid.min.js' %}"></script>
        <script type="text/javascript" src="{% static 'pronto/js/main.js' %}"></script>
        <link type="text/css" rel="stylesheet" href="{% static 'pronto/css/main.css' %}" />
        <title>Pronto Collection Home Page</title>
    </head>
    <body>
        {% csrf_token %}
        <div class ="main">
            <div class="header_left" >
                <div class="logo">
                    <img src= "{% static 'pronto/img/Nokia_logo.png' %}" width="220px" height="50px" border="0" alt="NOKIA" title="NOKIA">
                </div>
            </div>
            <div class="head-right" >
                <div class="content-top">
                    <div class="global_links f-right topNavBg">
                        <a href="{% url 'pronto:render_pronto_charting' %}">Report</a>
                        <a href="{% url 'pronto:render_pronto_statics' %}">Static</a>
                    </div>
                </div>
            </div>
            <div class="header_below">
                <ul>
                {% for filed_name in pronto_fields %}
                    <li><input type = "checkbox" name="{{ filed_name }}" id="{{ forloop.counter0 }}" value="{{ filed_name }}" onChange="chk({{ forloop.counter0 }},'{{ filed_name }}')" checked="checked"/> {{filed_name}}</li>
                {% endfor %}
                </ul>
            </div>
            <div id="jsGrid" class="main_table"></div>
            <script type="text/javascript">get_pronto_with_condition('get_pronto_all', true);</script>
        </div>
    </body>
</html>

pcs/pronto/templates/pronto/static.html
<!doctype html>
<html>
{% load static %}
    <head>
        <script type="text/javascript" src="{% static 'pronto/js/jquery.min.js' %}"></script>
        <script type="text/javascript" src="{% static 'pronto/js/highcharts.js' %}"></script>
        <script type="text/javascript" src="{% static 'pronto/js/charting.js' %}"></script>
        <link type="text/css" rel="stylesheet" href="{% static 'pronto/js/jsgrid-1.5.3/jsgrid.min.css' %}" />
        <link type="text/css" rel="stylesheet" href="{% static 'pronto/js/jsgrid-1.5.3/jsgrid-theme.min.css' %}" />
        <script type="text/javascript" src="{% static 'pronto/js/jsgrid-1.5.3/jsgrid.min.js' %}"></script>
        <script type="text/javascript" src="{% static 'pronto/js/main.js' %}"></script>
        <link type="text/css" rel="stylesheet" href="{% static 'pronto/css/main.css' %}" />
        <title>Pronto Collection Statics Page</title>
    </head>
    <body>
        {% csrf_token %}
        <div class ="main">
            <div class="header_left" >
                <div class="logo">
                    <img src= "{% static 'pronto/img/Nokia_logo.png' %}" width="220px" height="50px" border="0" alt="NOKIA" title="NOKIA">
                </div>
            </div>
            <div class="head-right" >
                <div class="content-top">
                    <div class="global_links f-right topNavBg">
                        <a href="{% url 'pronto:index' %}">Main</a>
                        <a href="{% url 'pronto:render_pronto_charting' %}">Report</a>
                    </div>
                </div>
            </div>
            <div class="charts">
                <div id="container_top_ratio" class="container_line_char">
                    <script type="text/javascript">stacked_percentage_column("container_top_ratio");</script>
                </div>
                <div id="container_priority_ratio" class="container_line_char">
                    <script type="text/javascript">stacked_percentage_column_priority("container_priority_ratio");</script>
                </div>
                <div id="container_pronto_cost" class="container_line_char">
                    <script type="text/javascript">get_pronto_time("container_pronto_cost");</script>
                </div>
                <div id="container_person" class="container_pie_chart">
                    <script type="text/javascript">pie_chart("container_person", "responsible_person");</script>
                </div>
                <div id="container_group" class="container_pie_chart">
                    <script type="text/javascript">pie_chart("container_group", "group_idx");</script>
                </div>
                <div id="container_status" class="container_pie_chart">
                    <script type="text/javascript">pie_chart("container_status", "status");</script>
                </div>
                <div id="container_group_to" class="container_pie_chart">
                    <script type="text/javascript">pie_chart("container_group_to", "transfer_to");</script>
                </div>
                <div id="container_group_from" class="container_pie_chart">
                    <script type="text/javascript">pie_chart("container_group_from", "transfer_from");</script>
                </div>
                <div id="container_severity" class="container_pie_chart">
                    <script type="text/javascript">pie_chart("container_severity", "severity");</script>
                </div>
                <div id="container_top" class="container_pie_chart">
                    <script type="text/javascript">pie_chart("container_top", "is_top");</script>
                </div>
            </div>
        </div>
    </body>
</html>